### ISSUE TITLE
请问electron-forge打包如何解决本地问题

### ISSUE THREAD

**Issue by kirbystudy** [dwtom/terran-palyer#2]

**Comment by kirbystudy** [comment]
报错信息：Uncaught TypeError: Failed to resolve module specifier "vue". Relative references must start with either "/", "./", or "../".

**Comment by dwtom** [comment]
打包之后vue项目是部署在服务器上的，和你正常开发上线一样

**Comment by kirbystudy** [comment]
我想通过本地来访问，不是线上。

**Comment by kirbystudy** [comment]
我通过 win.loadFile() 这样的方式访问，出现上面的报错信息。

**Comment by dwtom** [comment]
那vue项目就不要打包了直接loadurl吧，或者打包之后本地启动服务把vue项目起起来，你的报错可能是路径写的不对？？需要用__dirname那个，就算路径写对了，vue项目直接通过html打开也是不行的吧。

**Comment by kirbystudy** [comment]
昨天的问题解决了，我用了Electron Forge里的 Webpack Plugin插件，让他打包之后在本地启动一个服务。不然他找不到vue的模块。

**Comment by kirbystudy** [comment]
如果是用win.loadFile() 来访问 vue项目就不行，改成了win.loadURL()

**Comment by kirbystudy** [comment]
打包之后就用不了vite里面的2个自动导入的插件，需要自己把组件添加上。

**Comment by dwtom** [comment]
看到了一个插件[electron-vite](https://cn-evite.netlify.app/)不知道好不好用，我这个项目只是用来技术分享，后面大概也不会花太多精力继续迭代了。

**Comment by kirbystudy** [comment]
[electron-vite](https://cn-evite.netlify.app/) 这个挺好的，刚才试了一下，都给你全部配置好了，他这个是通过electron-builder来打包的
